# kubectl create secret generic t-wallet-secrets \
#   --from-literal=POSTGRES_USER=twallet \
#   --from-literal=POSTGRES_PASSWORD=<реальный_пароль> \
#   --from-literal=JWT_SECRET=<реальный_секрет>
apiVersion: v1
kind: Secret
metadata:
  name: t-wallet-secrets
type: Opaque
stringData:
  POSTGRES_USER: "twallet"
  POSTGRES_PASSWORD: "CHANGE_ME"
  JWT_SECRET: "CHANGE_ME"